2.0: MESH Hydrology parameters input file (Version 2.0)
##### Option Flags #####
----#
    0                                                       # Number of option flags
##### Channel routing parameters per river class #####
-------#
       0                                                    # Number of channel routing parameters
##### GRU class independent hydrologic parameters #####     # 10comment line 13                                                           | *
-------#                                                    # 11comment line 14                                                           | *
       0                                                    # Number of GRU independent hydrologic parameters
##### GRU class dependent hydrologic parameters #####       # 18comment line 16                                                           | *
-------#                                                    # 19comment line 17                                                           | *
       4                                                    # 21Number of GRU dependent hydrologic parameters                             | I8
!     1      2      5      6      8      10      14      15      16      17      18      19      
ZSNL  0.100  0.100  2.000  0.100  0.100  0.100   0.100   0.100   0.100   0.100   0.100   0.100
ZPLS  0.100  0.100  0.100  0.100  0.100  0.100   0.100   0.100   0.100   0.100   0.100   0.100
ZPLG  0.100  0.100  0.100  0.100  0.100  0.100   0.100   0.100   0.100   0.100   0.100   0.100
IWF   1      1      1      1      1      1       1       1       1       1       1       1
